### ISSUE TITLE
AttributeBag from POJO

### ISSUE THREAD

**Issue by benkuly** [authzforce/core#10]
Is there a way to create AttributeBags from POJOs?
Example:
```
Collection<String> values = ... ;
AttributeBag<?> attr = MagicClass.fromObject(values);
```

(I ask this because I want to switch from AT&T XACML to AuthZForce and [they had such a class](https://github.com/att/XACML/blob/df580ef6b1718467a78bac94e39a4716501a2b84/XACML/src/main/java/com/att/research/xacml/std/annotations/RequestParser.java).)

Edit 1:
I don't want to manually create e.g. a `StringValue`. At runtime I don't know of which java-type `values` is. It could be e.g. a `String` or a `LocalDataTime` or a `Collection<Integer>`.

**Comment by cdanger** [comment]
If I understand your example, yes, you can use the utility class `Bags` (same package as AttributeBag) for that. But you first need to convert Strings to StringValues for xacml string datatype, or AnyUriValue for anyURI datatype, etc. For example if you want string as attribute datatype, using Java 8 lambda expressions, you can do it as follows:

```java
Collection<String> values = ... ;
Collection<StringValue> attrValues = values.stream().map(StringValue::new).collect(Collectors.toList());
AttributeBag<StringValue> attrBag = Bags.newAttributeBag(StandardDatatypes.STRING, attributeValues);
```

You can replace `AttributeBag<StringValue>` with `AttributeBag<?>` of course if you don't care. This is just to show you that the API allows you to preserve the attribute value type info when creating the AttributeBag.

**Comment by benkuly** [comment]
Obviously my question was incomplete. Sorry for that. I edited it.

**Comment by cdanger** [comment]
Well, you know the original Java type used in the "POJO" obviously (thanks to the Reflection API). Then what AuthzForce needs to know is **which XACML datatype you want to map/convert it to**, for XACML policy evaluation. How does it know that?

In my previous example, I chose the XACML datatype `http://www.w3.org/2001/XMLSchema#string` (represented by `StringValue` class in AuthzForce Java API). But I could choose `http://www.w3.org/2001/XMLSchema#anyURI` (represented by `AnyUriValue` class in AuthzForce Java API) or whatever. Strings can be converted to any XACML datatype actually. So either you specify the XACML datatype you want explicitly, or you have to use some datatype mapping rules or algorithm (like JAXB has for mapping Java native types to XML datatypes and vice versa). 

As far as I understand the AT&T class you pointed to, with their implementation, you can specify your XACML datatypes in special AT&T-XACML-proprietary Java annotations in the POJO, e.g. `@XACMLSubject`, `@XACMLAction`, `@XACMLResource`; or, if you don't specify any, it falls back to mapping rules hardcoded in their [extractValue method](https://github.com/att/XACML/blob/df580ef6b1718467a78bac94e39a4716501a2b84/XACML/src/main/java/com/att/research/xacml/std/annotations/RequestParser.java#L311), as follows (excerpt):

- String -> http://www.w3.org/2001/XMLSchema#string
- Integer or Long -> http://www.w3.org/2001/XMLSchema#integer
- Boolean -> http://www.w3.org/2001/XMLSchema#boolean
- Double or Float -> http://www.w3.org/2001/XMLSchema#double
- Date or Calendar or ISO8601DateTime (this one is not native Java but AT&T-XACML proprietary) -> http://www.w3.org/2001/XMLSchema#dateTime
- URI -> http://www.w3.org/2001/XMLSchema#anyURI
...(there are about 10 other rules)...
- else (default) -> http://www.w3.org/2001/XMLSchema#string

Since in your example, you are not giving any info about the xacml datatype you want explicitly, I guess **you are interested in some automatic datatype mapping rules/algorithm, aren't you?**

On a side note, in your example, obviously you meant Local**Date**Time, not LocalDataTime. So I did a quick test of the AT&T-XACML with such type and here is what I get:

```
WARNING: Cannot decipher java object, defaulting to String datatype. If this is not correct, you must specify the datatype in the annotation.
```

So LocalDateTime is mapped to ... XACML **string** datatype (`http://www.w3.org/2001/XMLSchema#string)` with AT&T because it does not match any of the Java classes mapped to xacml dateTime. **Is this what you would like?**

**Comment by benkuly** [comment]
Thank you for this detailed answer.
Yes, AT&T-XACML will map LocalDateTime to String and that's not really the expected behavior. I think that's beacause they didn't updated their mapping (actually nobody is working on this framework).

>  I guess you are interested in some automatic datatype mapping rules/algorithm, aren't you?
Yes that's the point. But without annotations like in the AT&T-XACML. Just a simple static method.

_Just as a footnode: I'm working on a Spring Security integration of ABAC and AuthZForce is my favourite for the XACML-version of this integration._

**Comment by cdanger** [comment]
OK, we don't have such method ready yet. So let's make it a feature request. Spring Security integration is a big deal for us, so we can add this to the next release in a few days. One issue though is that we want to make these mappings configurable/extendable at runtime, because we can't anticipate every Java class out there that could be mapped to some XACML datatype, especially if you start using classes that are not in Java SE.

**Comment by cdanger** [comment]
Hello, we have an implementation ready for this feature in branch gh-10. I have created this [wiki page](https://github.com/authzforce/core/wiki/Default-Java-XACML-type-mappings-(TODO---issue-%2310)) to list the Java-to-XACML type mappings that it will provide. **Can you check this page to make sure this is OK for you before we release it?**

**Comment by benkuly** [comment]
Because of some maven-plugin problems when I import the branches into eclipse I did't tested it, but it would look like this. Is this the right use of the new feature?

(`RequestAttribute` is a class from my ABAC framework)

```
public DecisionRequest build(Collection<RequestAttribute> requestAttrs) {

	final DecisionRequestBuilder<?> requestBuilder = pdp.newRequestBuilder(-1, requestAttrs.size());

	for (RequestAttribute r : requestAttrs) {

		if (r.getValue() != null) {
			final AttributeFqn attributeId = AttributeFqns.newInstance(findCategory(r.getCategory()),
					Optional.empty(), r.getId());
			final AttributeBag<?> attributeValues = findAttributes(r.getValue());
			requestBuilder.putNamedAttributeIfAbsent(attributeId, attributeValues);
		}
		// TODO that should really never happen
		if (log.isDebugEnabled())
			log.debug("RequestAttribute with id '" + r.getId()
					+ "' will not be used in request because its value is null!");
	}
	return requestBuilder.build(false);
}

@SuppressWarnings("unchecked")
private AttributeBag<?> findAttributes(Object rawValue) {

	if (rawValue instanceof Serializable) {
		AttributeValue value = ATT_VALUE_FACTORIES.newAttributeValue((Serializable) rawValue);
		Bags.singletonAttributeBag(
				(Datatype<AttributeValue>) ATT_VALUE_FACTORIES.getExtension(value.getDataType()).getDatatype(),
				value);
	}
	if (rawValue instanceof Collection) {
		return ATT_VALUE_FACTORIES.newAttributeBag((Collection<? extends Serializable>) rawValue);
	}

	log.warn(
			"Cannot decipher java object, defaulting to String datatype. If this is not correct, you must specify the datatype in the annotation.");
	//
	// Default to a string
	//
	return Bags.singletonAttributeBag(StandardDatatypes.STRING, StringValue.parse(rawValue.toString()));
}
```

**Comment by cdanger** [comment]
Sounds good, except that if all you want is an AttributeBag in the end, you don't need to use the newAttributeValue() method, so you can simplify the `findAttributes` method like this:
```java
...
@SuppressWarnings("unchecked")
private AttributeBag<?> findAttributes(Object rawValue) {

	if (rawValue instanceof Serializable) {
		return ATT_VALUE_FACTORIES.newAttributeBag(Collections.singleton((Serializable) rawValue));
	}
	if (rawValue instanceof Collection) {
		return ATT_VALUE_FACTORIES.newAttributeBag((Collection<? extends Serializable>) rawValue);
	}

	log.warn(
			"Cannot decipher java object, defaulting to String datatype. If this is not correct, you must specify the datatype in the annotation.");
	//
	// Default to a string
	//
	return Bags.singletonAttributeBag(StandardDatatypes.STRING, StringValue.parse(rawValue.toString()));
}
```

**Comment by benkuly** [comment]
When will it be released? Or did I missed a snapshot in maven?
Thanks again!

**Comment by cdanger** [comment]
I was waiting for a *Yes, this is OK* kind of answer. So I take it as a Yes. I'll make the release in a day or two.

**Comment by benkuly** [comment]
Oh I'm sorry, I missed that.
Thank you very much!

**Comment by benkuly** [comment]
Thank you! 👍 
The new version needs `org.ow2.authzforce:authzforce-ce-core-pdp-api:jar:13.0.0`. This version isn't in maven central.

**Comment by cdanger** [comment]
Well, it is now:
https://repo.maven.apache.org/maven2/org/ow2/authzforce/authzforce-ce-core-pdp-api/13.0.0/
Don't know what went wrong with Maven Central publishing.
