### ISSUE TITLE
BaseNamedAttributeProvider is not of Type AbstractAttributeProvider

### ISSUE THREAD

**Issue by miladamery** [authzforce/core#26]
<dependency>
      <groupId>org.ow2.authzforce</groupId>
      <artifactId>authzforce-ce-core-pdp-api</artifactId>
     <version>15.0.0</version>
</dependency>

java version "1.8.0_131"

Windows 10

[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /F:/IntelijWorkspace/pip/src/main/java/AuthzPipTest/AuthzPipAttributeFactory.java:[11,94] type argument AuthzPipTest.TestAttributeProvider is not within bounds of type-variable CONF_T
[INFO] 1 error
[INFO] -------------------------------------------------------------

Hi. I'm trying to make an AttributeProvider that access database to resolve one attributeValue. i followed the steps in Wiki page to provide one. i finished it and when i wanted to create a package from it the top error occurs.
What my IDE says in the factory class is :
Type Parameter 'AuthzPipTest.TestAttributeProvide' is not within its bounds; should extend 'org.ow2.authzforce.xmlns.pdp.ext.AbstractAttributeProvider'

and no matter how much i search i cant find 'CloseableDesignatedAttributeProvider' file (.class or .java)
there is a 'CloseableNamedAttributeProvider' but the other one does not exists. i'm saying this because in wiki its mentioned that we need to implement 'CloseableDesignatedAttributeProvider' if we don't want to use 'BaseNamedAttributeProvider' but it does not exists.

**Comment by cdanger** [comment]
The type argument of your AttributeProvider factory must extend `AbstractAttributeProvider` indeed. In your AttributeProvider's XML schema (that defines the AttributeProvider's configuration model or format if you will), there must be a XML type that extends `AbstractAttributeProvider` (namespace `http://authzforce.github.io/xmlns/pdp/ext/3`), like `TestAttributeProvider` (namespace `http://authzforce.github.io/core/xmlns/test/3`) for example. As a result, the maven-jaxb2-plugin in your POM will generate a JAXB-annotated class from it (during the `generate-sources`phase of the build with Maven) which extends `org.ow2.authzforce.xmlns.pdp.ext.AbstractAttributeProvider` (also JAXB-annotated class corresponding to XML type `AbstractAttributeProvider`). For example, the class `org.ow2.authzforce.core.pdp.testutil.ext.xmlns.TestAttributeProvider` is generated from XML type `TestAttributeProvider` (during the build of `pdp-testutils` module). **This JAXB-annotated class is the one you must use as type argument.** So please check the JAXB classes generated (run maven generate-sources), one of them must extend AbstractAttributeProvider.

Use the [TestAttributeProvider](https://github.com/authzforce/core/blob/master/pdp-testutils/src/main/java/org/ow2/authzforce/core/pdp/testutil/ext/TestAttributeProvider.java) source code (for your version of authzforce-ce-core) as ultimate reference, if the doc is confusing or not up-to-date. Indeed, some class names were not up-to-date with the latest API:
- CloseableDesignatedAttributeProvider renamed to CloseableNamedAttributeProvider 
- BaseDesignatedAttributeProvider renamed to BaseNamedAttributeProvider

Thanks for reporting that, I fixed the wiki page. Sorry for the confusion :-( .

**Comment by miladamery** [comment]
thank you for answering but i don't get it still. in TestAttributeProvider class which is for reference we have
```
public class TestAttributeProvider extends BaseNamedAttributeProvider { ... }
```
and the factory class is like :
```
public static class Factory extends CloseableNamedAttributeProvider.FactoryBuilder<org.ow2.authzforce.core.pdp.testutil.ext.xmlns.TestAttributeProvider>
{
...
}
```
(what is that xmlns package?)
according to wiki this should work but it won't because BaseNamedAttributeProvider is not extended from AbstractAttributeProvider. 
then according to what you answered something like
```
public class TestAttributeProvider
    extends AbstractAttributeProvider implements CloseableNamedAttributeProvider { ... }
```
and using this type in factory will work. this is different from what wiki says.

**Comment by cdanger** [comment]
As I said, the class ...**.xmlns.TestAttributeProvider** - and so the *xmlns* package you are refering to - is **generated** automatically by Maven during the build. You will NOT find it anywhere in authzforce source code, because it is generated source code. This is **different from the class** ...**.ext.TestAttributeProvider** (different package!). The one in the xmlns package is your XML type **mapped to Java** (using JAXB), it is automatically generated by maven-jaxb2-plugin, and only represents the configuration parameters to your Attribute Provider. (Maybe we should name it TestAttributeProviderConfiguration to make the difference less subtle.) The other one is a class that must be written by you to implement the actual Attribute Provider's logic (retrieving the attribute(s)).

So, again, **what you should do first**, is run `$ mvn generate-sources` as told on the wiki; make sure some Java classes are generated by this command (based on your XML schema). They should end up in `target/generated-sources/xjc` usually or something like that. In any case, they should be automatically added to the build path. Finally, make sure that one of these generated class extends `AbstractAttributeProvider`. **Let me know what class is there.** You will use as type arg to the factory.

We don't mention `BaseNamedAttributeProvider` yet at this point, this is for the AttributeProvider's logic implementation.

**Comment by miladamery** [comment]
thank you for answering. i think now i get it. i was confused because of the same class names. i'm going to try again for creating custom attribute provider.
