### ISSUE TITLE
Dynamic Root Policy depending on the authorization request

### ISSUE THREAD

**Issue by samkeeleyong** [authzforce/core#44]
# Software version (AuthzForce Core)
15.1.1-SNAPSHOT (or latest as of writing)

# Problem
My particular use case is that for every authorization request, i have a corresponding policyset (either directly contains policies or links to other policysets) that i want to validate it against. Currently i have a root policy that links to everything, for example -->

Root
&nbsp;&nbsp;&nbsp;&nbsp;PS_1
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;P_1_1
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;P_1_2
&nbsp;&nbsp;&nbsp;&nbsp;PS_2
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;P_2_1

So that for one authz request (depending on some variable), i might only want to load everything under `PS_1` (and not PS_2) . I think i effectively want a dynamic root policy provider as mentioned [here](https://github.com/authzforce/restful-pdp/issues/2#issuecomment-410552225)? But this seems to be outdated since in the new way of writing `pdp.xml`, we only pass in one policy provider and then pass in the ID for the root.

How should I approach this problem?  I don't know at runtime how many "root" policies i might have.

**Comment by cdanger** [comment]
Depends on what _some variable_ is. Is it an authorization attribute by any chance? Or can we turn it into one? You are welcome to give an example.

**Comment by samkeeleyong** [comment]
So my `PS_1` looks like the one below:

```
<!-- Shortened for brevity --> 
<PolicySet ...>
       <Target>
              <Match MatchId="string-equals">
                         <AttributeValue>MyUuid-123</AttributeValue>
                         <AttributeDesignator AttributeId="....attrId:uuidToCheck" />
              </Match>
       </Target>
       <PolicyIdReference>...</PolicyIdReference>
       <PolicyIdReference>...</PolicyIdReference>
       ....
</PolicySet>
```

I would have a few of these with different `...attrId:uuidToCheck` in their Target elements.

And then I do a request via java (based on sample code on the README)
```
AttributeFqn uuidAttrId = AttributeFqns.newInstance("...", empty(), "....attrId:uuidToCheck");
AttributeBag<StringValue> uuidAttrValues = Bags.singleAttributeBag(STRING, new StringValue("MyUuid-123");

decisionRequestBuilder.putNamedAttributeIfAbsent(uuidAttrId, uuidAttrValues);
```

So when I do `new BasePdpEngine(pdpConfig)` I was hoping to only load the policyset `PS_1` and every other policy/policyset reference under it. I've been looking inside `PdpEngineConfiguration` and i know i can instantiate one by passing in a `Pdp` object and play around but i'm not sure if that would be a convoluted way of solving my problem. 

What do you mean by `authorization attribute` by the way? Attribute inside the policies or inside the authorization request?

**Comment by cdanger** [comment]
Are you also the poster on this Stackoverflow question?
https://stackoverflow.com/questions/60504584/dynamic-root-policyset-for-multi-tenancy-using-authzforce-core/60536625#60536625

I posted my answer there, so I think you shoud check it. 

By *authorization attribute*, I just mean an attribute that is either in the XACML Request or equivalent AuthzForce `DecisionRequest` (or any form of authorization request). In your case, this is the `uuidToCheck` attribute of a `DecisionRequest`.

So I see at least 2 possible solutions here (improved from my Stackoverflow answer):

# Option A
Use one `PdpEngine` instance (e.g. BasePdpEngine implementation in your case) per uuidToCheck value, i.e. dispatch the request to a specific `PdpEngine` instance based on this uuid value. For example a String-to-PdpEngine Map or smarter cache mechanism or whatever. So you would need as many PdpEngine instances as uuids I guess.

# Option B
Use the same PDP instance for all, as you are doing now, but apply these recommendations:
1. Use the `first-applicable` policy combining algorithm in the ROOT policy (so that the evaluation stops/returns at the first applicable - i.e. Target-matching - policyset within, no need to evaluate the others).
1. After testing the above, if you are still no satisfied with the performance, you can replace the ROOT policy's `first-applicable` algorithm with your own special policy combining algorithm by implementing an AuthzForce [CombiningAlgorithm extension](https://github.com/authzforce/core/wiki/XACML-Combining-Algorithms). In this custom algorithm, you would do the same mechanism as Option A basically: map the uuidToChecks to the matching PolicySets directly in a Java Map or whatever cache mechanism.
1. If still not satisfied with performance, you may implement and enable a global cache on the PdpEngine via an AuthzForce [Decision Cache](https://github.com/authzforce/core/wiki/Decision-Caches) extension.

**Comment by samkeeleyong** [comment]
Hello, really appreciate the response, and yes i was the poster to the SO question

For Option A, if i had like a thousand possible `uuidToCheck` values to check, (my use case is that the admins can play around with some weird permutation of rules), is that many `PdpEngine` instances okay? I think a String-to-PdpEngine with a good cache eviction strategy should help a lot but i am wondering if having a lot of `PdpEngine` instances is okay.

For Option B point number 2, I notice that when calling `new BasePdpEngine()`, it tries to resolve the root policy by loading it when setting the `rootPolicyEvaluator`. How does `first-applicable` work if i don't have the variable yet to differentiate it  (since i pass it along in the DecisionRequest) ?

**Comment by cdanger** [comment]
Option A has the obvious issue to use more memory, but I would expect the overhead not to be significant compared to option B. (In option B, instead of many PdpEngines, you will end up with one `PolicyEvaluator` instance per PolicySet for each `uuidToCheck` value. So that's as many PolicyEvaluators as PdpEngines in option A.)

The 'first-applicable' algorithm is described in XACML spec. In your case, it checks the Target of each PolicySet PS in the ROOT PolicySet and skips the policy unless there's a Match (on the uuidTocheck value). If there is, the PS is evaluated, and if the result is Permit/Deny, the evaluation stops there and this result is returned as the final result for the ROOT PolicySet. Done.

**Comment by samkeeleyong** [comment]
Hello, thank you very much. 

I understand what you mean by option A not being much overhead compared to option B. I created my own PdpEngine (mostly based on BasePdpEngine) and modified the root policy instantiation. I am now abe to load only the ones i want, and as you mentioned I have one `PolicyEvaluator` instance per `uuidToCheck`.
