### ISSUE TITLE
Support for ALFA language

### ISSUE THREAD

**Issue by lathspell** [authzforce/core#50]
As the engine already works with XACML, I wonder why ALFA is not supported. Isn't it supposed to be translatable to XACML? It would be far easier to write compared to XML.

With ALFA I mean the Abbreviated Language For Authorization as described on https://en.wikipedia.org/wiki/ALFA_(XACML) which seems to be an OASIS standard by now.

**Comment by cdanger** [comment]
Because the ALFA plugin for Eclipse already does the job of translating ALFA to XACML 3.0:
https://en.wikipedia.org/wiki/ALFA_(XACML)#The_ALFA_plugin_for_Eclipse

With this plugin, you may edit your ALFA policy in Eclipse, and get the XACML 3.0 version generated automatically in a separate folder of your project. More info about the plugin on Axiomatics website and Youtube. 

Also **beware ALFA is _not_ an OASIS standard** as of now. The ALFA specification has been submitted to the XACML TC in 2015 and is available there, for sure. But if you look at the spec, it still says _Working Draft 01_. It has not yet been voted on and approved by the TC, even as a Committee Specification Draft. There are five more steps to go before reaching the status of **OASIS standard** in the OASIS process. This is well explained on [Axiomatics website](https://www.axiomatics.com/blog/is-alfa-a-part-of-the-oasis-xacml-technical-committee-series-of-standards/) : _Is ALFA a Part of the OASIS XACML Technical Committee Series of Standards?_.

The OASIS TC standards track:
1. Committee Specification Draft,
1. Committee Specification Public Review Draft,
1. Committee Specification,
1. Candidate OASIS Standard,
1. **OASIS Standard**,
1. Approved Errata.

_(Disclaimer: I don't work for Axiomatics.)_

**Comment by lathspell** [comment]
I'm aware of that plugin but not everybody want's to install another IDE just to edit the rules files. I was thinking of ALFA as the format for editing and storing the policies and the conversion to XML as the very last step that is done internally because who wants an XML based configuration in 2020 :) Doesn't even have to be ALFA, just anything more readable than XACML.

**Comment by cdanger** [comment]
We have indeed a **JSON format for policies** that is closely equivalent to XACML, as well as means to translate back and forth automatically. This is not quite a DSL like ALFA, yet some consider it more readable than XACML. Would you be interested?

This is part of the [xacml-json-model project](https://github.com/authzforce/xacml-json-model), more specifically it provides:
- A JSON schema that formally defines this JSON policy format, [more info in the README](https://github.com/authzforce/xacml-json-model#xacmljson-policy-json-schema-and-validation);
- A few [examples of such JSON policies](https://github.com/authzforce/xacml-json-model/tree/develop/src/test/resources/xacml%2Bjson.samples/Policies/valid) for testing, with various levels of complexity;
- XSLT stylesheets to translate this JSON policies into XACML 3.0 automatically, with help of your favorite XSLT 3.0 library/processor, [more info in the README](https://github.com/authzforce/xacml-json-model#converting-xacmlxml-policyset-to-json-and-vice-versa), e.g. in a command line with SAXON XSLT library:
```
$ java -jar Saxon-HE-9.8.0-15.jar -xsl:xacml-policy-json-to-xml.xsl -it inJsonFile=MyPolicy.json
```

**Comment by lathspell** [comment]
Looks like the original XML transformed into JSON with all the boilerplate stuff like "urn:oasis:names:tc:xacml:1.0:function:string-equal" kept. To me this is as unreadable as XML and, being JSON and not YAML, even lacks the possibility to insert comments. (just that you understand my irritation: when reading "policy framework" I was thinking of something like a firewall system where you write rules as human readable text so that they can easily be prove-read. But I guess this is just not the right project for me :-))

**Comment by cdanger** [comment]
> I'm aware of that plugin but not everybody want's to install another IDE just to edit the rules files. 

Actually, I had not tried the ALFA plugin for a while, but I checked again, out of curiosity, if there was a way to just do the ALFA-to-XACML translation **outside Eclipse** in Java code or command-line, using one of the JARs inside the plugin package... and it turns out [there is ](https://stackoverflow.com/questions/28172464/use-alfa-in-standalone-mode/28304504#28304504)! Since ALFA 1.2 (2018). Thanks David Brossard for the heads up.

So you don't need the IDE anymore, as explained in ALFA 1.2 User Guide (provided with the plugin), in section _XACML generation using the standalone ALFA compiler_, you may translate ALFA policies with the `alfac.jar` provided (excerpt from the User Guide):

```
How to generate XACML output:

To generate XACML output from an alfa file test.alfa, use:
java -jar alfac.jar <path-to-test.alfa> <path-to-system.alfa> <path-to-standard-attributes.alfa>

To generate XACML output from alfa files in a directory alfaDir or its subdirectories, use:
java -jar alfac.jar <path-to-alfaDir>

To generate XACML output from alfa files in a directory alfaDir or its subdirectories inside a directory xacmlDir, use:
java -jar alfac.jar -o <path-to-xacmlDir> <path-to-alfaDir>

```

Feel free to try ALFA-to-XACML translation with this tool and check whether the XACML output works fine with AuthzForce.
