### ISSUE TITLE
Implementation help

### ISSUE THREAD

**Issue by killer136** [authzforce/core#58]
# Your code and/or AuthzForce-specific configuration file(s)
I am working on a solution where users can define multiple policy sets or Policies, now I want to load only specific policy/policy set in the PDP engine but I am not getting a way to do that in authzforce (PdpEngineConfiguration). Becuse pdp.xml expect to provide a "rootPolicyRef". How to instantiate the PDP engine with some other policy or policy set.

**Comment by cdanger** [comment]
What do you have in the `<policyProvider>` part of your pdp.xml?

**Comment by killer136** [comment]
Below is my pdp.xml, when I start my PDP engine it is loading the "airplane" policy set where the policy XML file stored in oracle DB and I am able to evaluate the XACML wrt to this policy.

But on a run time I want to load a different policy/policyset stored in  DB row, how can I do that? any pointer or some code example will be a great help. 

Thanks for your support

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<pdp xmlns="http://authzforce.github.io/core/xmlns/pdp/7.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="7.0.0">
<attributeProvider
   id="user"
   xmlns:user="com:example:identity:authorization:pip:user"
   xsi:type="user:PermissionAttributeProviderDescriptor"
   xmlns:xacml="urn:oasis:names:tc:xacml:3.0:core:schema:wd-17" >
</attributeProvider>
   <policyProvider
           id="refPolicyProvider"
           xmlns:policy="com:example:identity:authorization:pip:policy"
           xsi:type="policy:OracleDBBasedPolicyProviderDescriptor"
           xmlns:xacml="urn:oasis:names:tc:xacml:3.0:core:schema:wd-17">
   </policyProvider>
   <rootPolicyRef>airplane</rootPolicyRef>
</pdp>

**Comment by cdanger** [comment]
Well, if you want to change the root policy itself, if you to re-instantiate a new PdpEngineConfiguration with a different 'rootPolicyRef' (make sure to call pdpEngine.close() on the old one).

One other possibly is to use a specific attribute in the xacml request to apply a different policy(set), for example (this is pseudo code, not actual XACML but I hope you see how to translate that to XACML):

```
rootPolicySet:
      policy(Set)1:
         target match a=X
         ...child policies/rules...
      policySet2:
         target match a=Y
         ...child policies/rules...
```

In this case, you just change the value of attribute 'a' in the request to apply a different policy/policySet.

**Comment by killer136** [comment]
Thanks for your suggestion, but how this help to accommodate any policy at runtime. To be precise I am planning to add oracle DB as a policy store and the rest endpoint to perform basic CRUD operations on at any given point in time. Even with your approach, I will not be able to push policy to the PDP engine at runtime.

**Comment by cdanger** [comment]
Do you mean you want to do CRUD operations on XACML policies? like a PAP API (Policy Administration Point)?

**Comment by killer136** [comment]
Sorry, I was away for some time so couldn’t follow up. Yes exactly we are implementing our own PAP API for crud on XACML policies.

**Comment by cdanger** [comment]
OK. FYI you can look at [AuthzForce Server](https://github.com/authzforce/server) which provides a multi-tenant RESTful PAP/PDP API (each tenant/domain has its own PDP and a PAP API to manage the policies and the PDP config). In particular, the AuthzForce Server allows you to update the PDP's rootPolicyRef through the REST API, as described in the [User guide](https://authzforce-ce-fiware.readthedocs.io/en/latest/UserAndProgrammersGuide.html#policy-decision-pdp-properties):

```
HTTP PUT /domains/{domainId}/pap/pdp.properties
<pdpPropertiesUpdate xmlns="http://authzforce.github.io/rest-api-model/xmlns/authz/5">
...
 <rootPolicyRefExpression>mypolicy</rootPolicyRefExpression>
</pdpPropertiesUpdate>
```

Therefore, you can check the source code that implements this feature to see an example on how to update the PDP's root policy ref from a REST call. The method called is [DomainResourceImpl#updateOtherPdpProperties(...) ](https://github.com/authzforce/server/blob/master/rest-service/src/main/java/org/ow2/authzforce/rest/service/jaxrs/DomainResourceImpl.java#L618), which then calls at some point  [domainDao.setOtherPdpProperties(...)](https://github.com/authzforce/server/blob/master/rest-service/src/main/java/org/ow2/authzforce/rest/service/jaxrs/DomainResourceImpl.java#L629), where domainDao is configured by default (`domainsDaoBean` bean in the [Spring configuration](https://github.com/authzforce/server/blob/master/webapp/src/main/webapp/WEB-INF/beans.xml#L63) ) to be a FlatFileBasedDomainDao. So you'll find a concrete example in [FlatFileBasedDomainDao#setOtherPdpProperties](https://github.com/authzforce/pap-dao-flat-file/blob/master/src/main/java/org/ow2/authzforce/pap/dao/flatfile/FlatFileBasedDomainsDao.java#L1399), especially this part:

```java
pdpConf.setRootPolicyRef(rootPolicyRef);
reloadPDP(pdpConf);
```
So you could reuse this code to make your own PAP API. 

Or you can use AuthzForce Server directly but you need to provide your own data store implementation (for policies and PDP config) using Oracle DB, as we only provide a flat-file DB version (FlatFileBasedDomainsDao class). In order to implement a new data store (or more precisely a DAO interface) in AuthzForce Server,  you have to implement the interface [org.ow2.authzforce.core.pap.api.dao.DomainsDao](https://www.javadoc.io/doc/org.ow2.authzforce/authzforce-ce-core-pap-api/latest/org/ow2/authzforce/core/pap/api/dao/DomainsDao.html) - you can use our default [FlatFileBasedDomainsDao](https://github.com/authzforce/pap-dao-flat-file/blob/master/src/main/java/org/ow2/authzforce/pap/dao/flatfile/FlatFileBasedDomainsDao.java) implementation as example - and replace the FlatFileBasedDomainsDao with your new implementation class in the  [Spring configuration](https://github.com/authzforce/server/blob/master/webapp/src/main/webapp/WEB-INF/beans.xml#L63).

**Comment by cdanger** [comment]
No further comment, closing.
