### ISSUE TITLE
Question about Evaluating Requests in XACML/JSON format

### ISSUE THREAD

**Issue by nanoponge** [authzforce/core#60]
I can't find the example of PdpEngineXacmlJsonAdapters when I wanted to evaluate requests in JSON format. Can you give me the example of how to use JSON format to evaluate? Thank you!

**Comment by cdanger** [comment]
Check the section  _[Evaluating Requests in XACML/JSON format](https://github.com/authzforce/core/blob/develop/README.md#evaluating-requests-in-xacmljson-format)_ in the README. There's a link to the code of PdpEngineXacmlJsonAdapters that you can reuse/copy-paste. 
Then you'll need to parse your JSON requests into `org.json.JSONObject` objects in order to call the `PdpEngineInoutAdapter#evaluate(...)` method.

**Comment by nanoponge** [comment]
The link to the code of PdpEngineXacmlJsonAdapters can't be opened, and how can I get the code?

**Comment by cdanger** [comment]
Maybe you need to refresh the page ;-) 
Anyway here it is:
https://github.com/authzforce/core/blob/develop/pdp-testutils/src/test/java/org/ow2/authzforce/core/pdp/testutil/test/json/PdpEngineXacmlJsonAdapters.java

**Comment by cdanger** [comment]
No feedback. Closing.
